polish_statistic_pages
devdo-eu/capturenetwork pull request #43
Opened 2021-02-18 20:48 UTC by ppolakiewicz

I added bootstrap library to leaderboard page, 
add list of last 250 games with input to filter list.
Rename statistican.py to leaderboard.py cause we changed 
functionality of this package.

I know that our leaderboard page still looks very simple 
but it got all of funcionality so mabey I will add some style
later.

2021-02-19 08:30 UTC, devdo-eu approved these changes
Looks good 2 me

2021-02-19 08:42 UTC, devdo-eu requested changes

2021-02-19 08:42 UTC, devdo-eu commented on playbot/mind.py
> +        self.__my_name = f'RandBot_{randrange(1,100)}'
w8.
I change this line three weeks ago and erased random number part, so it was possible to rank ELO for this kind of bot.
With random name evaluation of ELO is near to impossible.
My last change was based on the assumption that the same bot cannot participate in a fight against itself - from the point of view of ELO calculation such a game is meaningless.

Another thing: `randrage(1,100)` - why range is so small? Despite drawing a number, probability of the same name is high and will occur for a range of 99 options (on average once in 99 games - so often)

Before my change the draw range was 500, set by me :P

2021-02-28 20:10 UTC, ppolakiewicz commented
As we talked offlien, I updated README about prepared bots

2021-02-28 20:46 UTC, devdo-eu commented
Please look at `polish_statistic_pages_changed` branch.
I was meaning changes like on `polish_statistic_pages_changed` branch when we talked offline.

2021-02-28 20:56 UTC, ppolakiewicz commented
> Please look at `polish_statistic_pages_changed` branch.
> I was meaning changes like on `polish_statistic_pages_changed` branch when we talked offline.

Hmm, I was convinced that moving bots to directories you wanted to do in the next step (PR).
Looks cool, then maybe in order not to waste your hard work, I will close this PR and open a new one from your branch ?

2021-03-02 19:55 UTC, ppolakiewicz commented
I cherry-pick your change.
Feel free to approve it 😄

2021-03-03 06:18 UTC, devdo-eu approved these changes

2021-03-03 06:18 UTC, merged